apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: default
spec:
  selector:
    matchLabels:
      app: zipkin
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2.12
        ports:
        - containerPort: 9411
        resources:
          limits:
            memory: 4Gi
            cpu: 1000m

---

apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: default
spec:
  type: NodePort
  selector:
    app: zipkin
  ports:
    - name: http
      protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 30200