# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: is_aruco_detector/conf/options.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='is_aruco_detector/conf/options.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$is_aruco_detector/conf/options.proto\"\xa4\x01\n\rArUcoSettings\x12$\n\ndictionary\x18\x01 \x01(\x0e\x32\x10.ArUcoDictionary\x12,\n\x07lengths\x18\x02 \x03(\x0b\x32\x1b.ArUcoSettings.LengthsEntry\x12\x0f\n\x07\x63\x61meras\x18\x03 \x03(\x03\x1a.\n\x0cLengthsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"`\n\x14\x41rUcoDetectorOptions\x12\x14\n\x0crabbitmq_uri\x18\x01 \x01(\t\x12\x12\n\nzipkin_uri\x18\x02 \x01(\t\x12\x1e\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x0e.ArUcoSettings*\xe9\x01\n\x0f\x41rUcoDictionary\x12\x0f\n\x0b\x44ICT_4X4_50\x10\x00\x12\x10\n\x0c\x44ICT_4X4_100\x10\x01\x12\x10\n\x0c\x44ICT_4X4_250\x10\x02\x12\x11\n\rDICT_4X4_1000\x10\x03\x12\x0f\n\x0b\x44ICT_5X5_50\x10\x04\x12\x10\n\x0c\x44ICT_5X5_100\x10\x05\x12\x10\n\x0c\x44ICT_5X5_250\x10\x06\x12\x11\n\rDICT_5X5_1000\x10\x07\x12\x0f\n\x0b\x44ICT_6X6_50\x10\x08\x12\x10\n\x0c\x44ICT_6X6_100\x10\t\x12\x10\n\x0c\x44ICT_6X6_250\x10\n\x12\x11\n\rDICT_6X6_1000\x10\x0b\x62\x06proto3'
)

_ARUCODICTIONARY = _descriptor.EnumDescriptor(
  name='ArUcoDictionary',
  full_name='ArUcoDictionary',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DICT_4X4_50', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DICT_4X4_100', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DICT_4X4_250', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DICT_4X4_1000', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DICT_5X5_50', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DICT_5X5_100', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DICT_5X5_250', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DICT_5X5_1000', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DICT_6X6_50', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DICT_6X6_100', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DICT_6X6_250', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DICT_6X6_1000', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=306,
  serialized_end=539,
)
_sym_db.RegisterEnumDescriptor(_ARUCODICTIONARY)

ArUcoDictionary = enum_type_wrapper.EnumTypeWrapper(_ARUCODICTIONARY)
DICT_4X4_50 = 0
DICT_4X4_100 = 1
DICT_4X4_250 = 2
DICT_4X4_1000 = 3
DICT_5X5_50 = 4
DICT_5X5_100 = 5
DICT_5X5_250 = 6
DICT_5X5_1000 = 7
DICT_6X6_50 = 8
DICT_6X6_100 = 9
DICT_6X6_250 = 10
DICT_6X6_1000 = 11



_ARUCOSETTINGS_LENGTHSENTRY = _descriptor.Descriptor(
  name='LengthsEntry',
  full_name='ArUcoSettings.LengthsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ArUcoSettings.LengthsEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ArUcoSettings.LengthsEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=205,
)

_ARUCOSETTINGS = _descriptor.Descriptor(
  name='ArUcoSettings',
  full_name='ArUcoSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dictionary', full_name='ArUcoSettings.dictionary', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lengths', full_name='ArUcoSettings.lengths', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cameras', full_name='ArUcoSettings.cameras', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ARUCOSETTINGS_LENGTHSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=205,
)


_ARUCODETECTOROPTIONS = _descriptor.Descriptor(
  name='ArUcoDetectorOptions',
  full_name='ArUcoDetectorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rabbitmq_uri', full_name='ArUcoDetectorOptions.rabbitmq_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zipkin_uri', full_name='ArUcoDetectorOptions.zipkin_uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='ArUcoDetectorOptions.config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=303,
)

_ARUCOSETTINGS_LENGTHSENTRY.containing_type = _ARUCOSETTINGS
_ARUCOSETTINGS.fields_by_name['dictionary'].enum_type = _ARUCODICTIONARY
_ARUCOSETTINGS.fields_by_name['lengths'].message_type = _ARUCOSETTINGS_LENGTHSENTRY
_ARUCODETECTOROPTIONS.fields_by_name['config'].message_type = _ARUCOSETTINGS
DESCRIPTOR.message_types_by_name['ArUcoSettings'] = _ARUCOSETTINGS
DESCRIPTOR.message_types_by_name['ArUcoDetectorOptions'] = _ARUCODETECTOROPTIONS
DESCRIPTOR.enum_types_by_name['ArUcoDictionary'] = _ARUCODICTIONARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArUcoSettings = _reflection.GeneratedProtocolMessageType('ArUcoSettings', (_message.Message,), {

  'LengthsEntry' : _reflection.GeneratedProtocolMessageType('LengthsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ARUCOSETTINGS_LENGTHSENTRY,
    '__module__' : 'is_aruco_detector.conf.options_pb2'
    # @@protoc_insertion_point(class_scope:ArUcoSettings.LengthsEntry)
    })
  ,
  'DESCRIPTOR' : _ARUCOSETTINGS,
  '__module__' : 'is_aruco_detector.conf.options_pb2'
  # @@protoc_insertion_point(class_scope:ArUcoSettings)
  })
_sym_db.RegisterMessage(ArUcoSettings)
_sym_db.RegisterMessage(ArUcoSettings.LengthsEntry)

ArUcoDetectorOptions = _reflection.GeneratedProtocolMessageType('ArUcoDetectorOptions', (_message.Message,), {
  'DESCRIPTOR' : _ARUCODETECTOROPTIONS,
  '__module__' : 'is_aruco_detector.conf.options_pb2'
  # @@protoc_insertion_point(class_scope:ArUcoDetectorOptions)
  })
_sym_db.RegisterMessage(ArUcoDetectorOptions)


_ARUCOSETTINGS_LENGTHSENTRY._options = None
# @@protoc_insertion_point(module_scope)
