---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: default
spec:
  type: NodePort
  selector:
    app: zipkin
  ports:
    - name: http
      protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 30200
