apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smarter-device-manager.fullname" . }}
  namespace: {{ include "smarter-device-manager.namespace" . }}
  labels:
    {{- include "smarter-device-manager.labels" . | nindent 4 }}
data:
  conf.yaml: |
        {{- toYaml .Values.devices | nindent 8 }}
