---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: default
spec:
  type: NodePort
  selector:
    app: cassandra
  ports:
    - name: http
      protocol: TCP
      port: 9042
      targetPort: 9042
      nodePort: 30201
