---
apiVersion: v1
kind: Service
metadata:
  name: is-mjpeg-server
  namespace: default
spec:
  type: NodePort
  selector:
    app: is-mjpeg-server
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300