# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='options.proto',
  package='is',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\roptions.proto\x12\x02is\"]\n\x08RabbitMQ\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x16\n\x0emanagement_url\x18\x05 \x01(\t\"E\n\x06Zipkin\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x10\n\x08loopback\x18\x02 \x01(\x04\x12\r\n\x05\x64rift\x18\x03 \x01(\r\x12\r\n\x05limit\x18\x04 \x01(\r\"|\n\x13IsControllerOptions\x12\r\n\x05timer\x18\x01 \x01(\r\x12\x1a\n\x06zipkin\x18\x02 \x01(\x0b\x32\n.is.Zipkin\x12\x1d\n\x07\x64\x65\x66\x61ult\x18\x03 \x01(\x0b\x32\x0c.is.RabbitMQ\x12\x1b\n\x05\x65\x64ges\x18\x04 \x03(\x0b\x32\x0c.is.RabbitMQb\x06proto3'
)




_RABBITMQ = _descriptor.Descriptor(
  name='RabbitMQ',
  full_name='is.RabbitMQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='is.RabbitMQ.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uri', full_name='is.RabbitMQ.uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='is.RabbitMQ.user', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='is.RabbitMQ.password', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='management_url', full_name='is.RabbitMQ.management_url', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=114,
)


_ZIPKIN = _descriptor.Descriptor(
  name='Zipkin',
  full_name='is.Zipkin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='is.Zipkin.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loopback', full_name='is.Zipkin.loopback', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drift', full_name='is.Zipkin.drift', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='is.Zipkin.limit', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=185,
)


_ISCONTROLLEROPTIONS = _descriptor.Descriptor(
  name='IsControllerOptions',
  full_name='is.IsControllerOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timer', full_name='is.IsControllerOptions.timer', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zipkin', full_name='is.IsControllerOptions.zipkin', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='default', full_name='is.IsControllerOptions.default', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edges', full_name='is.IsControllerOptions.edges', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=311,
)

_ISCONTROLLEROPTIONS.fields_by_name['zipkin'].message_type = _ZIPKIN
_ISCONTROLLEROPTIONS.fields_by_name['default'].message_type = _RABBITMQ
_ISCONTROLLEROPTIONS.fields_by_name['edges'].message_type = _RABBITMQ
DESCRIPTOR.message_types_by_name['RabbitMQ'] = _RABBITMQ
DESCRIPTOR.message_types_by_name['Zipkin'] = _ZIPKIN
DESCRIPTOR.message_types_by_name['IsControllerOptions'] = _ISCONTROLLEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RabbitMQ = _reflection.GeneratedProtocolMessageType('RabbitMQ', (_message.Message,), {
  'DESCRIPTOR' : _RABBITMQ,
  '__module__' : 'options_pb2'
  # @@protoc_insertion_point(class_scope:is.RabbitMQ)
  })
_sym_db.RegisterMessage(RabbitMQ)

Zipkin = _reflection.GeneratedProtocolMessageType('Zipkin', (_message.Message,), {
  'DESCRIPTOR' : _ZIPKIN,
  '__module__' : 'options_pb2'
  # @@protoc_insertion_point(class_scope:is.Zipkin)
  })
_sym_db.RegisterMessage(Zipkin)

IsControllerOptions = _reflection.GeneratedProtocolMessageType('IsControllerOptions', (_message.Message,), {
  'DESCRIPTOR' : _ISCONTROLLEROPTIONS,
  '__module__' : 'options_pb2'
  # @@protoc_insertion_point(class_scope:is.IsControllerOptions)
  })
_sym_db.RegisterMessage(IsControllerOptions)


# @@protoc_insertion_point(module_scope)
