---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: edge
spec:
  type: ClusterIP
  selector:
    app: zipkin
  ports:
    - name: http
      protocol: TCP
      port: 9411
      targetPort: 9411
