apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iscontrollers.labvisio.ufes.br
spec:
  scope: Namespaced
  group: labvisio.ufes.br
  names:
    kind: IsController
    plural: iscontrollers
    singular: iscontroller
    shortNames:
      - ic
      - ics
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cloud:
                  type: object
                  properties:
                    deployment:
                      type: object
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                        apiVersion:
                          type: string
                      required:
                      - name
                      - namespace
                      - apiVersion
                    rabbitmq_uri:
                      type: string
                  required:
                  - deployment
                  - rabbitmq_uri
                edge:
                  type: object
                  properties:
                    deployment:
                      type: object
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                        apiVersion:
                          type: string
                      required:
                      - name
                      - namespace
                      - apiVersion
                    rabbitmq_uri:
                      type: string
                  required:
                  - deployment
                  - rabbitmq_uri
                spans:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      service:
                        type: string
                    required:
                    - name
                    - service
              required:
              - edge
              - cloud
              - spans
          required:
          - spec