apiVersion: labvisio.ufes.br/v1
kind: IsController
metadata:
  name: aruco-controller
spec:
  cloud:
    deployment:
      name: is-aruco-detector
      namespace: default
      apiVersion: apps/v1
  edge:
    deployment:
      name: is-aruco-detector
      namespace: edge
      apiVersion: apps/v1
  spans:
  - name: frame
    service: cameragateway
  - name: localization
    service: aruco.localization
  tracesTargetValue: 12
  connections:
  - name: images
    src: edge
    dest: default
    topic: "CameraGateway.0.Frame"
  - name: tfs
    src: default
    dest: edge
    topic: "ArUco.0.FrameTransformations"