# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: is_robot/conf/options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='is_robot/conf/options.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bis_robot/conf/options.proto\"G\n\x0bRobotConfig\x12\x0f\n\x07\x63\x61meras\x18\x01 \x03(\x05\x12\x0e\n\x06\x61rucos\x18\x02 \x03(\x05\x12\x17\n\x0fprocessing_time\x18\x03 \x01(\x01\"V\n\x0cRobotOptions\x12\x14\n\x0crabbitmq_uri\x18\x01 \x01(\t\x12\x12\n\nzipkin_uri\x18\x02 \x01(\t\x12\x1c\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x0c.RobotConfigb\x06proto3'
)




_ROBOTCONFIG = _descriptor.Descriptor(
  name='RobotConfig',
  full_name='RobotConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cameras', full_name='RobotConfig.cameras', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arucos', full_name='RobotConfig.arucos', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processing_time', full_name='RobotConfig.processing_time', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=102,
)


_ROBOTOPTIONS = _descriptor.Descriptor(
  name='RobotOptions',
  full_name='RobotOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rabbitmq_uri', full_name='RobotOptions.rabbitmq_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zipkin_uri', full_name='RobotOptions.zipkin_uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='RobotOptions.config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=190,
)

_ROBOTOPTIONS.fields_by_name['config'].message_type = _ROBOTCONFIG
DESCRIPTOR.message_types_by_name['RobotConfig'] = _ROBOTCONFIG
DESCRIPTOR.message_types_by_name['RobotOptions'] = _ROBOTOPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotConfig = _reflection.GeneratedProtocolMessageType('RobotConfig', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTCONFIG,
  '__module__' : 'is_robot.conf.options_pb2'
  # @@protoc_insertion_point(class_scope:RobotConfig)
  })
_sym_db.RegisterMessage(RobotConfig)

RobotOptions = _reflection.GeneratedProtocolMessageType('RobotOptions', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTOPTIONS,
  '__module__' : 'is_robot.conf.options_pb2'
  # @@protoc_insertion_point(class_scope:RobotOptions)
  })
_sym_db.RegisterMessage(RobotOptions)


# @@protoc_insertion_point(module_scope)
