---
apiVersion: v1
kind: ConfigMap
metadata:
  name: is-calibration-server
  namespace: default
data:
  config: |-
    {
      "broker_uri": "amqp://rabbitmq.default:5672",
      "zipkin_uri": "http://zipkin.default:9411",
      "calibrations_path": "/opt/calibrations/etc/calibrations/ufes"
    }
