---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: is-calibration-server
spec:
  selector:
    matchLabels:
      app: is-calibration-server
  replicas: 1 
  template:
    metadata:
      labels:
        app: is-calibration-server
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      initContainers:
      - image: alpine/git
        name: git
        command:
        - git
        - clone
        - -b
        - develop
        - https://github.com/labviros/is-aruco-calib.git
        - /opt/calibrations
        volumeMounts:
        - name: calibrations
          mountPath: /opt/calibrations
      containers:
      - name: service 
        image: luizcarloscf/is-calibration-server:0.2.0
        command: ["is-calibration-server", "/etc/is-calibration-server/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1.0"
            memory: 128Mi
        volumeMounts:
        - name: options
          mountPath: /etc/is-calibration-server/
        - name: calibrations
          mountPath: /opt/calibrations
      volumes:
      - name: options
        configMap:
          name: is-calibration-server
          items:
          - key: config
            path: options.json
      - name: calibrations
        emptyDir: {}
      