# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: is_calibration_server/conf/options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='is_calibration_server/conf/options.proto',
  package='is',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(is_calibration_server/conf/options.proto\x12\x02is\"]\n\x18\x43\x61librationServerOptions\x12\x12\n\nbroker_uri\x18\x01 \x01(\t\x12\x12\n\nzipkin_uri\x18\x02 \x01(\t\x12\x19\n\x11\x63\x61librations_path\x18\x03 \x01(\tb\x06proto3'
)




_CALIBRATIONSERVEROPTIONS = _descriptor.Descriptor(
  name='CalibrationServerOptions',
  full_name='is.CalibrationServerOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='broker_uri', full_name='is.CalibrationServerOptions.broker_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zipkin_uri', full_name='is.CalibrationServerOptions.zipkin_uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='calibrations_path', full_name='is.CalibrationServerOptions.calibrations_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['CalibrationServerOptions'] = _CALIBRATIONSERVEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalibrationServerOptions = _reflection.GeneratedProtocolMessageType('CalibrationServerOptions', (_message.Message,), {
  'DESCRIPTOR' : _CALIBRATIONSERVEROPTIONS,
  '__module__' : 'is_calibration_server.conf.options_pb2'
  # @@protoc_insertion_point(class_scope:is.CalibrationServerOptions)
  })
_sym_db.RegisterMessage(CalibrationServerOptions)


# @@protoc_insertion_point(module_scope)
