---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: default
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7.6-management
        imagePullPolicy: Always
        ports:
        - containerPort: 5672
        - containerPort: 1883
        - containerPort: 15675
        - containerPort: 15672
        resources:
          limits:
            memory: 2Gi
            cpu: "2"
        volumeMounts:
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq/
      volumes:
      - name: rabbitmq-config
        configMap:
          name: rabbitmq
          items:
          - key: plugins
            path: enabled_plugins
          - key: config
            path: rabbitmq.conf
          - key: definitions
            path: definitions.json
