---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30000
    - name: managment
      protocol: TCP
      port: 80
      targetPort: 15672
      nodePort: 30080
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 30001
    - name: web-mqtt
      protocol: TCP
      port: 15675
      targetPort: 15675
      nodePort: 30002