---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: edge
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30003
    - name: managment
      protocol: TCP
      port: 80
      targetPort: 15672
      nodePort: 30083
